language: ruby
sudo: false
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.2.0.0

env:
  global:
    # --dev improves JRuby startup time
    # See https://github.com/jruby/jruby/wiki/Improving-startup-time
    - JRUBY_OPTS="--dev"

gemfile:
  - Gemfile

services:
- mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
